# The Neural Networks Playground Project

In [10]:
import numpy as np
import pandas as pd
from NeuralNetwork import NeuralNetwork

In [ ]:
Binary2DecimalNN = NeuralNetwork(2, (3, 2), 4)

In [ ]:
neural_network_description = f"""This Neural Network has {Binary2DecimalNN.number_of_inputs} inputs, {Binary2DecimalNN.number_of_outputs} outputs, {Binary2DecimalNN.number_of_dense_layers} dense layers and {Binary2DecimalNN.neurons_per_layer} neurons per layer."""

print(neural_network_description)

In [11]:
data = {"x_0": [0, 0, 0, 0, 1, 1, 1, 1],
        "x_1": [0, 0, 1, 1, 0, 0, 1, 1],
        "x_2": [0, 1, 0, 1, 0, 1, 0, 1],
        "y_0": [1, 0, 0, 0, 0, 0, 0, 0],
        "y_1": [0, 1, 0, 0, 0, 0, 0, 0],
        "y_2": [0, 0, 1, 0, 0, 0, 0, 0],
        "y_3": [0, 0, 0, 1, 0, 0, 0, 0],
        "y_4": [0, 0, 0, 0, 1, 0, 0, 0],
        "y_5": [0, 0, 0, 0, 0, 1, 0, 0],
        "y_6": [0, 0, 0, 0, 0, 0, 1, 0],
        "y_7": [0, 0, 0, 0, 0, 0, 0, 1]}

dataset = pd.DataFrame(data)

dataset

x_0  x_1  x_2  y_0  y_1  y_2  y_3  y_4  y_5  y_6  y_7
0    0    0    0    1    0    0    0    0    0    0    0
1    0    0    1    0    1    0    0    0    0    0    0
2    0    1    0    0    0    1    0    0    0    0    0
3    0    1    1    0    0    0    1    0    0    0    0
4    1    0    0    0    0    0    0    1    0    0    0
5    1    0    1    0    0    0    0    0    1    0    0
6    1    1    0    0    0    0    0    0    0    1    0
7    1    1    1    0    0    0    0    0    0    0    1

In [12]:
x = dataset[["x_0", "x_1", "x_2"]]
y = dataset[[c for c in dataset.columns if c not in x.columns]]

x = x.to_numpy()
y = y.to_numpy()

In [13]:
x

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]], dtype=int64)

In [14]:
y

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [ ]:
from NeuronLayer import NeuronLayer
from ActivationFunctions import Sigmoid
from CostFunctions import MeanSquaredError

In [ ]:
Layer = NeuronLayer(3, 8, Sigmoid)

In [ ]:
ActivationFunction = Sigmoid()
CostFunction = MeanSquaredError()

In [ ]:
y_estimate = Layer.feed_forward(x)

y_estimate

In [ ]:
CostFunction.cost(y, y_estimate)

In [ ]:
dC_dA = CostFunction.cost_derivative(y, y_estimate)

dA_dZ = ActivationFunction.activation_derivative(y_estimate)

dZ_dW = x

In [ ]:
dC_dA

In [ ]:
dA_dZ

In [ ]:
dZ_dW

In [ ]:
dC_dW = dC_dA @ dA_dZ @ dZ_dW

dC_dW

In [ ]:
alpha = 0.2

In [ ]:
new_weights = Layer.weights - alpha * dC_dW.T

new_weights

In [ ]:
Layer.weights = new_weights

In [ ]:
def back_propagate(x, y, y_estimate, Layer, alpha):
    
    C_dA = CostFunction.cost_derivative(y, y_estimate)

    dA_dZ = ActivationFunction.activation_derivative(y_estimate)

    dZ_dW = x
    
    dC_dW = dC_dA @ dA_dZ @ dZ_dW
    
    new_weights = Layer.weights - alpha * dC_dW.T
    
    Layer.weights = new_weights

In [ ]:
for i in range(2000):
    back_propagate(x, y, y_estimate, Layer, alpha)

In [ ]:
Layer.feed_forward(x)

In [ ]:
Layer.feed_forward(np.array([1, 1]))

In [ ]:
Layer.weights @ dA_dZ @ dC_dA

In [ ]:
C_dA = CostFunction.cost_derivative(y, y_estimate)

dA_dZ = ActivationFunction.activation_derivative(y_estimate)

dZ_dW = x
    
dC_dW = dC_dA * dA_dZ * dZ_dW
    
#new_weights = Layer.weights - alpha * dC_dW.T

In [ ]:
Layer.weights @ (dC_dA * dA_dZ)

In [ ]:
(dC_dA * dA_dZ) @ Layer.weights.T

In [ ]:
np.round(dC_dA, 2)

In [ ]:
np.round(dA_dZ, 2)

In [ ]:
np.round(dC_dA * dA_dZ, 2)

In [ ]:
Layer.weights @ (dA_dZ * dC_dA)

In [ ]:
Layer.weights

In [ ]:
a = np.random.randint(1, 5, size=(8, 5))
a

In [ ]:
b = np.random.randint(0, 10, size=(8, 5))
b

In [ ]:
np.mean(a, axis=0)

In [ ]:
a * b

In [ ]:
(dC_dA * dA_dZ) * x

In [ ]:
(1/2) * np.mean((y_estimate - y)**2, axis=0)

In [ ]:
np.array([[2, 3, 4], [1, -9, 7]])**2

In [ ]:
y.shape

In [ ]:
y_estimate.shape

In [ ]:
samples, outputs = y.shape

In [ ]:
loss = CostFunction.cost_derivative(y, y_estimate)
loss = loss.reshape((1, outputs))

loss

In [ ]:
((loss * dA_dZ) @ x).T

In [ ]:
np.array([2, 3, 4]) * np.array([[2, 3, 4], [1, -9, 7], [0, 0.5, 0.25]])

In [ ]:
Layer.weights.shape

# Let's Test This in a More Seriuos Way

In [1]:
from NeuronLayer import NeuronLayer
from ActivationFunctions import Sigmoid
from CostFunctions import MeanSquaredError

## Set Things Up

In [2]:
NUMBER_OF_INPUTS = 3
NUMBER_OF_OUTPUTS = 8
NEURONS_PER_LAYER = 5

In [5]:
ActivationFunction = Sigmoid
CostFunction = MeanSquaredError

In [6]:
FirstLayer = NeuronLayer(NUMBER_OF_INPUTS, NEURONS_PER_LAYER, ActivationFunction)
SecondLayer = NeuronLayer(NEURONS_PER_LAYER, NUMBER_OF_OUTPUTS, ActivationFunction)

## Start Computing

### 1. FeedForward

In [21]:
FirstLayer.feed_forward(x)

array([[0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.56629676, 0.57282604, 0.60955625, 0.60830436, 0.59851536],
       [0.60646436, 0.60490568, 0.71045841, 0.55386138, 0.62803761],
       [0.66801749, 0.6724614 , 0.7929925 , 0.65846809, 0.71567134],
       [0.72429791, 0.71302924, 0.6024369 , 0.64027444, 0.691729  ],
       [0.77428023, 0.76915266, 0.70288553, 0.73433822, 0.76985594],
       [0.80192291, 0.79184623, 0.78805494, 0.68844085, 0.79117495],
       [0.84092329, 0.83609851, 0.85304527, 0.77434853, 0.84957929]])

In [22]:
z0 = FirstLayer.output
a0 = FirstLayer.activation

In [28]:
SecondLayer.feed_forward(a0)

array([[0.82650212, 0.69637553, 0.77309684, 0.7272095 , 0.7745309 ,
        0.76428434, 0.75164362, 0.70654924],
       [0.8639953 , 0.72808209, 0.80911931, 0.75891399, 0.81286563,
        0.80201897, 0.78714369, 0.73678977],
       [0.87354957, 0.73672051, 0.82742935, 0.76890899, 0.81523566,
        0.82191655, 0.78961956, 0.75020217],
       [0.89919626, 0.76258992, 0.85243253, 0.79442717, 0.84548385,
        0.8476705 , 0.81877475, 0.77412896],
       [0.89021655, 0.75487736, 0.83707455, 0.79286787, 0.840778  ,
        0.82577715, 0.8188971 , 0.76677984],
       [0.91164187, 0.77769641, 0.86073907, 0.81438006, 0.86509022,
        0.85128766, 0.84204825, 0.78845287],
       [0.91659057, 0.78321633, 0.87195825, 0.82037368, 0.86594001,
        0.86405271, 0.84280259, 0.79731882],
       [0.92984733, 0.79948909, 0.88633888, 0.83562032, 0.88328507,
        0.87913955, 0.8599665 , 0.81223817]])

In [32]:
z1 = SecondLayer.output
a1 = SecondLayer.activation

### 2. BackPropagation

In [64]:
dC_dA1 = CostFunction().cost(y, a1).reshape(1, NUMBER_OF_OUTPUTS)
dA1_dZ1 = ActivationFunction().activation_derivative(z1)
dZ1_dW1 = a0

In [68]:
(dC_dA1 * dA1_dZ1) @ dZ1_dW1

array([[0.29495407, 0.29377925, 0.29924367, 0.27747642, 0.29836612],
       [0.26424046, 0.26321822, 0.26851458, 0.24870058, 0.2674828 ],
       [0.25425258, 0.25325949, 0.25823217, 0.23922131, 0.25733562],
       [0.22767826, 0.22681765, 0.23162567, 0.21434678, 0.23060301],
       [0.23670503, 0.23580827, 0.24064441, 0.22291309, 0.23970293],
       [0.21234279, 0.21156367, 0.21620543, 0.20008591, 0.21517438],
       [0.20539483, 0.2046341 , 0.20903212, 0.19348133, 0.20810415],
       [0.1878376 , 0.18716302, 0.19142345, 0.17705019, 0.19042702]])

In [91]:
SecondLayer.weights.shape

(5, 8)

In [73]:
dZ1_dA0 = SecondLayer.weights
dA0_dZ0 = ActivationFunction().activation_derivative(z0)
dZ0_dW0 = x

In [88]:
(dC_dA1 * dA1_dZ1) @ dZ1_dA0.T @ dA0_dZ0.T @ dZ0_dW0

array([[0.69346208, 0.72698399, 0.74769173],
       [0.61461055, 0.64445067, 0.66282139],
       [0.58946214, 0.61840305, 0.63578279],
       [0.5226454 , 0.54839482, 0.56383469],
       [0.54619802, 0.57269945, 0.58909243],
       [0.48536204, 0.50901845, 0.52359071],
       [0.4683022 , 0.49137153, 0.50524733],
       [0.42514819, 0.44613703, 0.45876293]])

In [92]:
FirstLayer.weights.shape

(3, 5)

# Now in a More Serious Way (Add One Layer and Split Dataset into Train and Test)

In [1]:
from NeuronLayer import NeuronLayer
from ActivationFunctions import Sigmoid
from CostFunctions import MeanSquaredError

## Set Things Up

In [2]:
NUMBER_OF_INPUTS = 3
NUMBER_OF_OUTPUTS = 8
NEURONS_PER_LAYER = 5

In [3]:
ActivationFunction = Sigmoid
CostFunction = MeanSquaredError

In [4]:
InputLayer = NeuronLayer(NUMBER_OF_INPUTS, NEURONS_PER_LAYER, ActivationFunction)
HiddenLayer = NeuronLayer(NEURONS_PER_LAYER, NEURONS_PER_LAYER, ActivationFunction)
OutputLayer = NeuronLayer(NEURONS_PER_LAYER, NUMBER_OF_OUTPUTS, ActivationFunction)

In [64]:
print(f"""Neuron Architecture: {InputLayer.weights.shape} by {HiddenLayer.weights.shape} by {OutputLayer.weights.shape}.""")

Neuron Architecture: (3, 5) by (5, 5) by (5, 8).


## Train-Test Split

In [73]:
TOTAL_SAMPLES = x.shape[0]
TRAINING_PERCENTAGE = 80
TRAIN_SAMPLES = int(np.floor(TRAINING_PERCENTAGE * TOTAL_SAMPLES / 100))
TEST_SAMPLES = int(TOTAL_SAMPLES - TRAIN_SAMPLES)

In [74]:
print(f"""There are {TRAIN_SAMPLES} train samples and {TEST_SAMPLES} test samples.""")

There are 6 train samples and 2 test samples.


In [78]:
x_train = x[0:TRAIN_SAMPLES]
x_test = x[TRAIN_SAMPLES:]

y_train = y[0:TRAIN_SAMPLES]
y_test = y[TRAIN_SAMPLES:]

## Start Computing

### 1. FeedForward

#### Input Layer

In [81]:
InputLayer.feed_forward(x_train)

array([[0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.62502381, 0.71809583, 0.67714023, 0.65836728, 0.68514117],
       [0.56284025, 0.72165111, 0.61328003, 0.56131166, 0.72185861],
       [0.68214011, 0.86849333, 0.76884149, 0.71146581, 0.84956588],
       [0.55983122, 0.56265073, 0.55632599, 0.72471034, 0.66559659],
       [0.67948462, 0.76619742, 0.7245061 , 0.83534259, 0.81242369]])

In [82]:
z0 = InputLayer.output
a0 = InputLayer.activation

#### Hidden Layer

In [85]:
HiddenLayer.feed_forward(a0)

array([[0.72260072, 0.84688542, 0.80928319, 0.78126444, 0.75803131],
       [0.78628199, 0.90888047, 0.87627444, 0.85032984, 0.82434497],
       [0.77436516, 0.90125139, 0.86473158, 0.83560352, 0.8111514 ],
       [0.81884871, 0.93556899, 0.90558232, 0.88071542, 0.85547307],
       [0.77855877, 0.88976156, 0.85958008, 0.82097144, 0.80146836],
       [0.82307822, 0.93096639, 0.90444634, 0.87400939, 0.85174592]])

In [86]:
z1 = HiddenLayer.output
a1 = HiddenLayer.activation

#### Output Layer

In [89]:
OutputLayer.feed_forward(a1)

array([[0.82823353, 0.76970666, 0.93152007, 0.84505241, 0.86268879,
        0.94639104, 0.81531604, 0.90043057],
       [0.84636402, 0.78698966, 0.94407792, 0.86297482, 0.87923142,
        0.95734824, 0.83251013, 0.91596222],
       [0.84323026, 0.78401177, 0.94204862, 0.85970593, 0.87666387,
        0.95556218, 0.82979451, 0.91327942],
       [0.85437617, 0.79444004, 0.94905289, 0.87035326, 0.88593695,
        0.96164498, 0.83972985, 0.92233386],
       [0.84242763, 0.78215725, 0.94063979, 0.85688192, 0.87448966,
        0.95447829, 0.8270504 , 0.91185943],
       [0.85441052, 0.79386978, 0.94863908, 0.86927749, 0.88520413,
        0.96135964, 0.83869996, 0.92196905]])

In [90]:
z2 = OutputLayer.output
a2 = OutputLayer.activation

### 2. BackPropagation

#### Output Layer

In [93]:
dC_dA2 = CostFunction().cost(y_train, a2).reshape(1, NUMBER_OF_OUTPUTS)
dA2_dZ2 = ActivationFunction().activation_derivative(z2)
dZ2_dW2 = a1

In [109]:
dC_dZ2 = (dA2_dZ2 * dC_dA2)

In [113]:
dC_dW2 = dZ2_dW2.T @ dC_dZ2

#### Hidden Layer

In [114]:
dZ2_dA1 = OutputLayer.weights
dA1_dZ1 = ActivationFunction().activation_derivative(z1)
dZ1_dW1 = a0

In [135]:
(dA1_dZ1 @ dZ2_dA1) @ dC_dZ2.T

array([[0.1116404 , 0.09876462, 0.1009508 , 0.09334475, 0.10237222,
        0.09377897],
       [0.0827701 , 0.07318217, 0.07481116, 0.06914589, 0.07586178,
        0.06946485],
       [0.08819916, 0.07798977, 0.07972433, 0.07369194, 0.0808447 ,
        0.07403252],
       [0.0678475 , 0.05996509, 0.06130492, 0.05664659, 0.06216441,
        0.05690644],
       [0.09194275, 0.08131397, 0.08311944, 0.0768401 , 0.08429029,
        0.07719716],
       [0.06929443, 0.06125164, 0.06261858, 0.05786593, 0.06349825,
        0.05813258]])

(5, 8)